#!/bin/bash

TAMOUNT=$(zenity --entry --title="Set Countdown.." --text="..In Minutes")

at now +$TAMOUNT minutes <<ENDMARKER

touch ~/Desktop/restart.log

date +%H:%M >> ~/Desktop/restart.log

sleep 2

sudo shutdown -r now

ENDMARKER
